CREATE TYPE DOIS_VALORES AS (SOMA INTEGER, PRODUTO INTEGER);

CREATE FUNCTION SOMA_E_PRODUTO (NUMERO_1 INTEGER, NUMERO_2 INTEGER)RETURNS DOIS_VALORES AS $$ 
	SELECT NUMERO_1 + NUMERO_2 AS SOMA, NUMERO_1 * NUMERO_2 AS PRODUTO;
$$ LANGUAGE SQL;

SELECT * FROM SOMA_E_PRODUTO(3,3);