CREATE TABLE INSTRUTOR (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	SALARIO DECIMAL(10, 2)
);

ALTER TABLE INSTRUTOR
RENAME TO "INSTRUTOR"

INSERT INTO "INSTRUTOR" (nome, salario)
VALUES
	   ('Diogo Mascarenhas', 200.00),
	   ('Nico Steppat', 300.00),
	   ('juliana', 400.00),
	   ('Priscila', 500.00);

CREATE FUNCTION DOBRO_DO_SALARIO("INSTRUTOR") RETURNS DECIMAL AS $$
	SELECT $1.SALARIO * 2 AS DOBRO
$$ LANGUAGE SQL;


SELECT * FROM "INSTRUTOR";

SELECT *, DOBRO_DO_SALARIO ("INSTRUTOR".*) FROM "INSTRUTOR";

CREATE OR REPLACE FUNCTION CRIA_INSTRUTOR_FALSO() RETURNS "INSTRUTOR" AS $$
	SELECT 22, 'Nome falso', 200::DECIMAL;
$$ LANGUAGE SQL;

SELECT ID, SALARIO FROM cria_instrutor_falso()

DROP FUNCTION INSTRUTORES_BEM_PAGOS;

CREATE FUNCTION INSTRUTORES_BEM_PAGOS(VALOR_SALARIO DECIMAL) RETURNS SETOF "INSTRUTOR" AS $$ 
	SELECT * FROM "INSTRUTOR" WHERE SALARIO > VALOR_SALARIO;
$$ LANGUAGE SQL;

SELECT * FROM INSTRUTORES_BEM_PAGOS(300);