CREATE OR REPLACE FUNCTION PRIMEIRA_PL() RETURNS INTEGER AS $$ 
	DECLARE
		PRIMEIRA_VARIAVEL INTEGER DEFAULT 3;
	BEGIN
		PRIMEIRA_VARIAVEL := PRIMEIRA_VARIAVEL * 2;	
		RETURN PRIMEIRA_VARIAVEL;
	END
$$ LANGUAGE PLPGSQL;

SELECT PRIMEIRA_PL();